---
title: "Data manipulation"
output: github_document
---

```{r}
library(tidyverse)

```

## Load in the FAS litters data
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

choose some columns and not others
```{r}

select(litters_df, group, litter_number)
```
```{r}

select(litters_df, group, gd0_weight:gd_of_birth)
```
```{r}

select(litters_df, -litter_number)
```

Renaming columins
```{r}

select(litters_df, GROUP = group, LIITER_NO = litter_number)
```

```{r}
rename(litters_df, GROUP = group)
```

Select helpers
```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```
```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}

filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth ==20))
```
```{r}

filter(litters_df, gd_of_birth != 20)
```

```{r}

filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
```
```{r}
filter(litters_df, group %in% c("Mod8", "Con7"))
```
## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## ` arange`
```{r}
arrange(litters_df, pups_born_alive)
```
## `%>%`

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_cleaning = janitor::clean_names(litters_data_raw)
litters_select = select(litters_cleaning, -pups_survive)
litters_mutate = mutate(litters_select, wt_gain = gd18_weight - gd0_weight)
littes_without_mising = drop_na(litters_mutate, gd0_weight)
```

Use the PIPE operate instead
```{r}
litter_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate (wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight) %>% 
  spec()
```


